name: "â¬†ï¸ publish"

on:
    release:
        types: [published]

jobs:
    release:
        name: â¬†ï¸ publish
        runs-on: ubuntu-latest
        steps:
            - name: checkout ğŸ“š
              uses: actions/checkout@v2.1.1
            - name: node ğŸŸ¢
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org
            - name: â¬†ï¸ publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}